name: .NET Core CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
