name: .NET Core CI
on: [push, workflow_dispatch, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - run: docker pull camunda/zeebe:1.0.0
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
  auto-merge:
    name: Auto-merge dependabot PRs
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.repository == 'camunda-community-hub/zeebe-client-csharp' && github.actor == 'dependabot[bot]'
    permissions:
      checks: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - id: metadata
        name: Fetch dependency metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - id: merge
        name: Merge PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
