name: .NET Core CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - run: docker pull camunda/zeebe:1.0.0
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
