name: Release Client
on: 
  push:
    branches:
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Pack 
      working-directory: ./Client
      run: dotnet pack --configuration Release --no-restore
